openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Apifecol
  description: "Documentación API Facturación Electrónica DIAN."
  contact:
    name: "Juan Bautista"
    email: "soyjuanbautista0@gmail.com"
  license:
    name: "GNU General Public License v3.0"
    url: "https://github.com/juanbautista0/apifecol/blob/main/LICENSE"
servers:
  - url: "http://localhost:8025"
    description: "Server"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /info:
    get:
      tags:
        - "Status"
      summary: "(ES): Obtener estado de API. (EN): Get API status."
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /login/login:
    post:
      tags:
        - "Login"
      summary: "(ES): Obtener token de sesión. (EN): Get session token."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tenancy:
                  type: string
                email:
                  type: string
                password:
                  type: string
                NIT:
                  type: string
            example: # Sample object
              tenancy: apifecol
              email: juan.bautista@plenusservices.com
              password: your_password
              NIT: 901004305
      responses:
        202:
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Access permission denied
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/listings:
    get:
      tags:
        - "Listados"
      summary: "(ES): Ver listados de configuraciones y valores DIAN. (EN): See list of DIAN configurations and values."
      produces:
        - "application/json"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/listings/rows/{source}/{id}:
    get:
      tags:
        - "Listados"
      summary: "(ES): Listado de configuraciones y valores DIAN. (EN): List of DIAN configurations and values."
      produces:
        - "application/json"
      parameters:
        - name: source
          in: path
          description: recurso y/o esquema
          required: true
          type: string
          format: string
        - name: id
          in: path
          description: identificador
          required: false
          type: integer
          format: int
          default:
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/company/config/{nit}:
    get:
      tags:
        - "Empresas"
      summary: "(ES): Obtener datos de empresa por nit. (EN): Obtain company data by nit."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
    put:
      tags:
        - Empresas
      summary: "(ES): Actualización de datos de empresa por nit. (EN):Update of company data by nit."
      parameters:
        - name: nit
          in: path
          description: NIT de empresa"
          required: true
          schema:
            type: integer
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              required:
                - nit_type_id
                - type_organization_id
                - type_regime_id
                - liability_id
                - business_name
                - merchant_registration
                - municipality_id
                - address
                - phone
                - email
              properties:
                name:
                  description: Nombre de la empresa
                  type: string
                business_name:
                  description: Nombre comercial
                  type: string
                identification_number:
                  description: NIT/CC
                  type: integer
                language_id:
                  description: Código de idioma
                  type: integer
                  default: 53
                tax_id:
                  description: Código de impuesto
                  type: integer
                  default: 1
                type_environment_id:
                  description: Código del ambiente
                  type: integer
                  default: 2
                nit_type_id:
                  description: Código de tipo de documento de identificación
                  type: integer
                  default: 6
                country_id:
                  description: Código del pais
                  type: integer
                  default: 53
                type_currency_id:
                  description: Código del tipo moneda por defecto
                  type: integer
                  default: 52
                type_organization_id:
                  description: Código del tipo organización
                  type: integer
                type_regime_id:
                  description: Código del tipo regimen
                  type: integer
                  default: 1
                liability_id:
                  description: Código del tipo responsabilidad
                  type: integer
                municipality_id:
                  description: Código del municipio
                  type: integer
                  default: 111
                merchant_registration:
                  description: Matrícula mercantil
                  type: string
                  default: N/A
                software_id:
                  description: Identificador del software (DIAN)
                  type: string
                pin:
                  description: Pin del software (DIAN)
                  type: string
                test_id:
                  description: Código del SET de pruebas (DIAN).
                  type: string
                printing_format:
                  description: Formato de representación gráfica
                  type: string
                  default: "1"
                send_method:
                  description: "Método de envio de documentos (DIAN: SendBillSync = 1, SendBillAsync = 2, SendTestSetAsync = 3)"
                  type: integer
                  default: 3
                address:
                  description: Dirección
                  type: string
                phone:
                  description: Teléfono
                  type: integer
                email:
                  description: Correo electrónico
                  type: string
                  format: email
                certificate:
                  description: Certificado para firma electrónica (.pfx) codificado en base64
                  type: string
                certificate_password:
                  description: Contraseña de certificado
                  type: string
                certificate_validity:
                  description: Vigencia del certificado en formato yyyy-mm-dd
                  type: date
                host_email:
                  description: Host/servidor de correo smtp
                  type: string
                host_port:
                  description: Puerto del host/servidor de correo smtp
                  type: string
                host_username:
                  description: Cuenta de correo para el envío de documento (correo@miempresa.com)
                  type: string
                host_password:
                  description: Contraseña de cuenta de correo para el envío de documento
                  type: string
                image:
                  description: Logo de la empresa codificado en base 64
                  type: string
                status:
                  description: Estado de la empresa
                  type: integer
                  default: 1
              example:
                name: PLENUSSERIVCES S.A.S
                business_name: Plenus Services
                identification_number: 901004305
                language_id: 53
                tax_id: 1
                type_environment_id: 2
                country_id: 52
                type_currency_id: 52
                type_regime_id: 1
                liability_id: 1
                nit_type_id: 6
                municipality_id: 111
                merchant_registration: A25584542
                address: AV siempre viva 742
                phone: 94268952
                email: correo@miempresa.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                items: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                items: {}
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                items: {}
      post:
        tags:
          - Empresas
        summary: "(ES): Creación de empresa. (EN): Create company."
        parameters:
          - name: nit
            in: path
            description: NIT de empresa"
            required: true
            schema:
              type: integer
        requestBody:
          description: Objeto para actualizar la empresa.
          required: true
          content:
            application/json:
              schema:
                required:
                  - nit_type_id
                  - type_organization_id
                  - type_regime_id
                  - liability_id
                  - business_name
                  - merchant_registration
                  - municipality_id
                  - address
                  - phone
                  - email
                properties:
                  name:
                    description: Nombre de la empresa
                    type: string
                  business_name:
                    description: Nombre comercial
                    type: string
                  identification_number:
                    description: NIT/CC
                    type: integer
                  language_id:
                    description: Código de idioma
                    type: integer
                    default: 53
                  tax_id:
                    description: Código de impuesto
                    type: integer
                    default: 1
                  type_environment_id:
                    description: Código del ambiente
                    type: integer
                    default: 2
                  nit_type_id:
                    description: Código de tipo de documento de identificación
                    type: integer
                    default: 6
                  country_id:
                    description: Código del pais
                    type: integer
                    default: 53
                  type_currency_id:
                    description: Código del tipo moneda por defecto
                    type: integer
                    default: 52
                  type_organization_id:
                    description: Código del tipo organización
                    type: integer
                  type_regime_id:
                    description: Código del tipo regimen
                    type: integer
                    default: 1
                  liability_id:
                    description: Código del tipo responsabilidad
                    type: integer
                  municipality_id:
                    description: Código del municipio
                    type: integer
                    default: 111
                  merchant_registration:
                    description: Matrícula mercantil
                    type: string
                    default: N/A
                  software_id:
                    description: Identificador del software (DIAN)
                    type: string
                  pin:
                    description: Pin del software (DIAN)
                    type: string
                  test_id:
                    description: Código del SET de pruebas (DIAN).
                    type: string
                  printing_format:
                    description: Formato de representación gráfica
                    type: string
                    default: "1"
                  send_method:
                    description: "Método de envio de documentos (DIAN: SendBillSync = 1, SendBillAsync = 2, SendTestSetAsync = 3)"
                    type: integer
                    default: 3
                  address:
                    description: Dirección
                    type: string
                  phone:
                    description: Teléfono
                    type: integer
                  email:
                    description: Correo electrónico
                    type: string
                    format: email
                  certificate:
                    description: Certificado para firma electrónica (.pfx) codificado en base64
                    type: string
                  certificate_password:
                    description: Contraseña de certificado
                    type: string
                  certificate_validity:
                    description: Vigencia del certificado en formato yyyy-mm-dd
                    type: date
                  host_email:
                    description: Host/servidor de correo smtp
                    type: string
                  host_port:
                    description: Puerto del host/servidor de correo smtp
                    type: string
                  host_username:
                    description: Cuenta de correo para el envío de documento (correo@miempresa.com)
                    type: string
                  host_password:
                    description: Contraseña de cuenta de correo para el envío de documento
                    type: string
                  image:
                    description: Logo de la empresa codificado en base 64
                    type: string
                  status:
                    description: Estado de la empresa
                    type: integer
                    default: 1
                example:
                  name: PLENUSSERIVCES S.A.S
                  business_name: Plenus Services
                  identification_number: 901004305
                  language_id: 53
                  tax_id: 1
                  type_environment_id: 2
                  country_id: 52
                  type_currency_id: 52
                  type_regime_id: 1
                  liability_id: 1
                  nit_type_id: 6
                  municipality_id: 111
                  merchant_registration: A25584542
                  address: AV siempre viva 742
                  phone: 94268952
                  email: correo@miempresa.com
        responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          "400":
            description: Bad Request
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          "401":
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          "404":
            description: Not Found
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          "422":
            description: Unprocessable Entity
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          "500":
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: object
                  items: {}
      delete:
        tags:
          - "Listados"
        summary: "(ES): Listado de configuraciones y valores DIAN. (EN): List of DIAN configurations and values."
        produces:
          - "application/json"
        parameters:
          - name: source
            in: path
            description: recurso y/o esquema
            required: true
            type: string
            format: string
          - name: id
            in: path
            description: identificador
            required: false
            type: integer
            format: int
            default:
        responses:
          200:
            description: Ok
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          404:
            description: Not Found
            content:
              application/json:
                schema:
                  type: object
                  items: {}
          500:
            description: Server error
            content:
              application/json:
                schema:
                  type: object
                  items: {}
    post:
      tags:
        - Empresas
      summary: "(ES): Creación de empresa. (EN): Create company."
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          schema:
            type: integer
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              required:
                - name
                - business_name
                - identification_number
                - nit_type_id
                - language_id
                - tax_id
                - nit_type_id
                - type_organization_id
                - type_regime_id
                - liability_id
                - merchant_registration
                - municipality_id
                - address
                - phone
                - email
              properties:
                name:
                  description: Nombre de la empresa
                  type: string
                business_name:
                  description: Nombre comercial
                  type: string
                identification_number:
                  description: NIT/CC
                  type: integer
                language_id:
                  description: Código de idioma
                  type: integer
                  default: 53
                tax_id:
                  description: Código de impuesto
                  type: integer
                  default: 1
                type_environment_id:
                  description: Código del ambiente
                  type: integer
                  default: 2
                nit_type_id:
                  description: Código de tipo de documento de identificación
                  type: integer
                  default: 6
                country_id:
                  description: Código del pais
                  type: integer
                  default: 53
                type_currency_id:
                  description: Código del tipo moneda por defecto
                  type: integer
                  default: 52
                type_organization_id:
                  description: Código del tipo organización
                  type: integer
                type_regime_id:
                  description: Código del tipo regimen
                  type: integer
                  default: 1
                liability_id:
                  description: Código del tipo responsabilidad
                  type: integer
                municipality_id:
                  description: Código del municipio
                  type: integer
                  default: 111
                merchant_registration:
                  description: Matrícula mercantil
                  type: string
                  default: N/A
                software_id:
                  description: Identificador del software (DIAN)
                  type: string
                pin:
                  description: Pin del software (DIAN)
                  type: string
                test_id:
                  description: Código del SET de pruebas (DIAN).
                  type: string
                printing_format:
                  description: Formato de representación gráfica
                  type: string
                  default: "1"
                send_method:
                  description: "Método de envio de documentos (DIAN: SendBillSync = 1, SendBillAsync = 2, SendTestSetAsync = 3)"
                  type: integer
                  default: 3
                address:
                  description: Dirección
                  type: string
                phone:
                  description: Teléfono
                  type: integer
                email:
                  description: Correo electrónico
                  type: string
                  format: email
                certificate:
                  description: Certificado para firma electrónica (.pfx) codificado en base64
                  type: string
                certificate_password:
                  description: Contraseña de certificado
                  type: string
                certificate_validity:
                  description: Vigencia del certificado en formato yyyy-mm-dd
                  type: date
                host_email:
                  description: Host/servidor de correo smtp
                  type: string
                host_port:
                  description: Puerto del host/servidor de correo smtp
                  type: string
                host_username:
                  description: Cuenta de correo para el envío de documento (correo@miempresa.com)
                  type: string
                host_password:
                  description: Contraseña de cuenta de correo para el envío de documento
                  type: string
                image:
                  description: Logo de la empresa codificado en base 64
                  type: string
                status:
                  description: Estado de la empresa
                  type: integer
                  default: 1
              example:
                name: PLENUSSERIVCES S.A.S
                business_name: Plenus Services
                identification_number: "901004305"
                language_id: 53
                tax_id: 1
                type_environment_id: 2
                country_id: 52
                type_currency_id: 52
                type_regime_id: 1
                liability_id: 1
                nit_type_id: 6
                municipality_id: 111
                merchant_registration: A25584542
                printing_format: "1"
                address: AV siempre viva 742
                phone: 94268952
                email: correo@miempresa.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                items: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        "409":
          description: Conflict

          content:
            application/json:
              schema:
                type: object
                items: {}
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                items: {}
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                items: {}
    delete:
      tags:
        - "Empresas"
      summary: "(ES): Eliminar empresa por nit. (EN): Company delete by nit."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/config/software/{nit}:
    put:
      tags:
        - "Configuración"
      summary: "(ES): Configuración de software. (EN): Software config."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: string
          format: string
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              properties:
                software_id:
                  description: Identificador del software (DIAN)
                  type: string
                pin:
                  description: Pin del software (DIAN)
                  type: string
                test_id:
                  description: Identificador de pruebas (DIAN)
                  type: string
            example:
              software_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              pin: "94266"
              test_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/config/certificate/{nit}:
    put:
      tags:
        - "Configuración"
      summary: "(ES): Actualización de certificado. (EN): Certificate update."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: string
          format: string
      requestBody:
        description: Objeto el certificado.
        required: true
        content:
          application/json:
            schema:
              properties:
                certificate:
                  description: Certificado de firmar electrónica codifcado en base64
                  type: string
                certificate_password:
                  description: Contraseña del certificado
                  type: string
                certificate_validity:
                  description: Vigencia del certificado yyyy-mm-dd
                  type: string
                  format: date
            example:
              certificate: "base64"
              certificate_password: "********"
              certificate_validity: "2021-05-26"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/config/logo/{nit}:
    put:
      tags:
        - "Configuración"
      summary: "(ES): Actualizar logo empresa. (EN): Company logo update."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: string
          format: string
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              properties:
                logo:
                  description: Imagen de logo en codificada en base64
                  type: string
            example:
              logo: "base64"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/resolution/config/{nit}/{id}:
    get:
      tags:
        - "Resoluciones"
      summary: "(ES): Resoluciones de facturación (DIAN). (EN): Resolutions billing (DIAN)."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
        - name: id
          in: path
          description: ID resolución
          required: false
          type: string
          format: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
    put:
      tags:
        - "Resoluciones"
      summary: "(ES): Actualizar resolución de facturación (DIAN). (EN): Update billing resolution (DIAN)."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
        - name: id
          in: path
          description: ID resolución
          required: false
          type: integer
          format: int
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              required:
                - type_document_id
                - prefix
                - resolution
                - resolution_date
                - technical_key
                - from
                - to
                - date_from
                - date_to
              properties:
                type_document_id:
                  description: Identificador de tipo de documento
                  type: integer
                  format: int
                prefix:
                  description: Prefijo de facturación
                  type: string
                resolution:
                  description: Número de resolución (DIAN)
                  type: integer
                resolution_date:
                  description: Fecha de resolución
                  type: date
                  format: yyyy-mm-dd
                technical_key:
                  description: Llave técnica (DIAN)
                  type: string
                  format: string
                from:
                  description: Rango desde
                  type: integer
                  format: int
                to:
                  description: Rango hasta
                  type: integer
                  format: int
                date_from:
                  description: Fecha desde
                  type: date
                  format: yyyy-mm-dd
                date_to:
                  description: Fecha hasta
                  type: date
                  format: yyyy-mm-dd
              example:
                type_document_id: 1
                prefix: "ps"
                resolution: "23478789878987"
                resolution_date: "2021-02-15"
                technical_key: "sdg47s7g89sdf7h987sdh78989h7897s8ghs89h78"
                from: 1
                to: 1000
                date_from: "2021-02-15"
                date_to: "2022-02-15"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
    delete:
      tags:
        - "Resoluciones"
      summary: "(ES): Eliminar resolución de facturación (DIAN). (EN): Delete billing resolution (DIAN)."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
        - name: id
          in: path
          description: ID resolución
          required: false
          type: integer
          format: int
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
  /modules/v1/resolution/config/{nit}:
    post:
      tags:
        - "Resoluciones"
      summary: "(ES): Crear resolución de facturación (DIAN). (EN): Create billing resolution (DIAN)."
      produces:
        - "application/json"
      parameters:
        - name: nit
          in: path
          description: NIT de empresa
          required: true
          type: integer
          format: int
      requestBody:
        description: Objeto para actualizar la empresa.
        required: true
        content:
          application/json:
            schema:
              required:
                - type_document_id
                - prefix
                - resolution
                - resolution_date
                - technical_key
                - from
                - to
                - date_from
                - date_to
              properties:
                type_document_id:
                  description: Identificador de tipo de documento
                  type: integer
                  format: int
                prefix:
                  description: Prefijo de facturación
                  type: string
                resolution:
                  description: Número de resolución (DIAN)
                  type: integer
                resolution_date:
                  description: Fecha de resolución
                  type: date
                  format: yyyy-mm-dd
                technical_key:
                  description: Llave técnica (DIAN)
                  type: string
                  format: string
                from:
                  description: Rango desde
                  type: integer
                  format: int
                to:
                  description: Rango hasta
                  type: integer
                  format: int
                date_from:
                  description: Fecha desde
                  type: date
                  format: yyyy-mm-dd
                date_to:
                  description: Fecha hasta
                  type: date
                  format: yyyy-mm-dd
              example:
                type_document_id: 1
                prefix: "ps"
                resolution: "23478789878987"
                resolution_date: "2021-02-15"
                technical_key: "sdg47s7g89sdf7h987sdh78989h7897s8ghs89h78"
                from: 1
                to: 1000
                date_from: "2021-02-15"
                date_to: "2022-02-15"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                items: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                items: {}
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                items: {}
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                items: {}
